config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "swirls#index"
  resources :swirls
  resources :abouts
  get "stores/random", to: 'stores#random'
  resources :stores , shallow: true do
    resources :comments
    resources :ratings
  end
  resources :shares
  resources :users, only:[:new, :create]
  resources :sessions, only:[:new, :create, :destroy]

  get '/login', to: 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :store
  belongs_to :user
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :store

  
end

app/models/share.rb
class Share < ApplicationRecord
    validates :nickname, presence: true
    validates :content, presence:true
    validates :location, presence:true
    validates :image_content_type, presence:true
end

app/models/store.rb
class Store < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :contact_info, presence:true
    validates :location, presence:true
    has_many :comments, dependent: :destroy 
    has_many :ratings, dependent: :destroy 


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    # Verify that an email exists and that it does not already exist in the db
    validates :email, presence: true, uniqueness: true
    validates :name, presence: true
    has_many :comments
    has_many :ratings
    
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

    def index
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    private

    helper_method :current_user
    #makes this make the current user called into the views

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
    
    def authorize
      redirect_to login_path, alert:'unauthorized entry- you must be logged in' if current_user.nil?
    end

    helper_method :average_rating
    
    def average_rating store 
        store_id = store.id
        rating = Rating.where(store_id: store_id)
        sum = 0
        rating.each do |rating|
          sum += rating.rating
        end
        if rating.count == 0
          0
        else        
          sum.to_f / rating.count
        end
      end
   

    
end

app/controllers/comments_controller.rb
class CommentsController <ApplicationController
    def index
    end

    def new
        @comment =Comment.new
        @store = Store.find(params[:store_id])
        end

    def create
        @comment = Comment.new(comment_params)
        @comment.store_id = params[:store_id]
        @comment.user_id = current_user.id
        
        if @comment.save
          
            redirect_to store_path(params[:store_id])
        else 
            render :new

        end
    end

    # def show
    #     @store = Store.find(params[:store_id])
    #     @user = User.find(params[:user_id])
    #     @comment = Comment.new
    # end

    def update
        @comment = Comment.find(params[:id])
    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_back(fallback_location: stores_path)
    end

private

    def comment_params
        params.require(:comment).permit(:comment)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    def create
        store = Store.find(params[:store_id])
        rating = Rating.find_by(:user => current_user, :store => store)
        unless rating
            store.ratings.create(user: current_user, rating: params[:rating])
        end
        redirect_to store_path(store)
    end
    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
    
    def create
        user = User.find_by(email: params[:email])
        # logging in
        if user && user.authenticate(params[:password])
            # if the user logging in matches the info theny log in
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in!"
        else
            flash.now.alert =  "Nope!! Do it again!"
            render :new
        end
        
    end 
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "You done?!"
    end
    

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
    def index
        @shares= Share.all
    
    end

    def new
        @share= Share.new
    end
    
    def create
        @share = Share.new(params.require(:share).permit(:nickname, :location, :image_content_type, :content))
        if @share.save
            redirect_to shares_path
        else
            render :new
        end
    end   
    private
        def share_params
            params.require(:share).permit(:image_content_type, :nickname, :content, :location)
        end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    
    before_action only: [:show, :edit, :update, :destroy]
    before_action :authorize, except: [:index]
    def index
        @stores = Store.all
    end
    
    def show
        @store = Store.find(params[:id])
        @comment = Comment.new
    end

    def new
        @store = Store.new
    end
    
    def create
        @store = Store.new(params.require(:store).permit(:name, :location, :contact_info, :image_content_type))
        if @store.save
            redirect_to stores_path
        else
            render :new
        end
    end   

    def edit
        @store = Store.find(params[:id])
    end
    
    def update
        @store = Store.find(params[:id])
        if @store.update_attributes(store_params)
            redirect_to store_path
        else
            render :edit
        end

    end
    

    def destroy
        @store = Store.find(params[:id])
        @store.destroy
        redirect_to stores_path
       
    end

    def random
        @store = Store.all.to_a.sample
        @comment = Comment.new
        redirect_to store_path(@store) 
    end


    private

        def store_params
            params.require(:store).permit(:image_content_type, :name, :contact_info, :location)
        end    
end

app/controllers/swirls_controller.rb
class SwirlsController < ApplicationController

    def index
       
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end

    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            # above is to help keep the user keep the session going after they log in
            redirect_to root_path
        else
            render :new
        end
    end
    
private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmatiom)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swirls Of Joy</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Bungee+Shade|Londrina+Sketch" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Marvel" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag "icon.png" %>
  </head>

  <body class="container">

  <nav class="navbar navbar-fixed-top">
 
  <h4 class= swirls><%= link_to image_tag("icon.png", {width: 40}), swirls_path %>&nbsp SOJ </h4> &nbsp&nbsp&nbsp
  <div id="logger">  
    <p>
      <% if current_user %>   
        Welcome, <%= current_user.name %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
      <% else %>
        <%= link_to 'Log In', login_path %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'Sign Up', new_user_path %>
      <% end %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
<p><%= link_to 'Stores', stores_path %></p>
&nbsp;&nbsp;|&nbsp;&nbsp;
<p><%= link_to 'Share My Cone', shares_path %></p>
&nbsp;&nbsp;|&nbsp;&nbsp;
<p><%= link_to 'About Us', abouts_path %></p>
    </p>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/shares/index.html.erb
<div class="swirls">
    <h1>Share my Cone</h1>
        <h3>Feel free to post your opinions, pictures and<br> where you found some awesome ice cream</h3>
        <%= link_to "Create a Post", new_share_path %>
</div>
<div>    
    <div class="font">
        <dl class= "profile">
            <% @shares.each do |share| %>
            <div class= "center">
                <div class="button">
                    <div class="bckclr">
                        <dl><%= image_tag share.image_content_type, size: "370x300" %></dl>
                            <dd>Nickname:<%= share.nickname %> </dd>
                            <dd>Location:<%= share.location %></dd>
                            <dd>Comments:<%= share.content %></dd>
                    </div>
                </div>
            </div>
            <% end %>
        </dl>
    </div>
</div>



   
   

app/views/shares/new.html.erb
<h3>POST!</h3>
<%= form_for @share do |share| %>
   <div class="field">
        <%= share.label :nickname %>
        <%= share.text_field :nickname %>
    </div>
    <div class="field">
        <%= share.label :location %>&nbsp&nbsp
        <%= share.text_field :location %>
    </div>
    <div class="field">
        <%= share.label :content %>&nbsp&nbsp&nbsp
        <%= share.text_field :content %>
    </div>
    <div class="field">
       <p class="bold">Url_image<%= share.url_field :image_content_type %></p>
    </div>
    <div class="actions"><%= share.submit %></div>
    <% end %>

app/views/stores/edit.html.erb
<h1>Edit <%= @store.name %></h1>

<%= form_for @store do |s| %>
 
    <div class="field">
      <%= s.label :name %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= s.text_field :name %>
    </div>
    <div class="field">
      <%= s.label :location %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= s.text_field :location %>
    </div>
    <div class="field">
      <%= s.label :contact_info %>
      <%= s.text_field :contact_info %>
    </div>
    <div class="field">
      <% s.label :image_content_type %>
      <p class="bold">Image url <%= s.url_field :image_content_type %></p>
    </div>
      <div class="actions"><%= s.submit "Update Store" %></div>
  
<% end %>

app/views/stores/index.html.erb
<h2 class="font2">Store Locations</h2>
<h3 class="font2"><%= link_to '+Add Stores', new_store_path %></h3>
<div class="font">
    <dl class= "profile">
        <% @stores.each do |store| %>
        <div class="bckclr">
            <dl><%= image_tag store.image_content_type, size: "370x300" %></dl>
                <dd><%= link_to store.name, store_path(store) %> </dd>
                <dd><%= store.location %></dd>
                <dd><%= store.contact_info %></dd>
                <dd>Rating:<%= average_rating(store) %> </dd>
        </div>
        <% end %>
    </dl>
</div>

app/views/stores/new.html.erb
<div class="font2"><h1>New Location</h1></div>

<%= form_for @store do |s| %>
 
    <div class="field">
      <%= s.label :name %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= s.text_field :name %>
    </div>
    <div class="field">
      <%= s.label :location %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= s.text_field :location %>
    </div>
    <div class="field">
      <%= s.label :contact_info %>
      <%= s.text_field :contact_info %>
    </div>
    <div class="field">
      <% s.label :image_content_type %>
      <p class="bold">Image url <%= s.url_field :image_content_type %></p>
    </div>
      <div class="actions"><%= s.submit %></div>
  
<% end %>

<% link_to "Return to Stores", stores_path %>

app/views/stores/show.html.erb
 <div class="font2">   
    <h2><%= @store.name %></h2>
</div>        
 <div class="font">
    <p><%= image_tag @store.image_content_type, size: "370x300" %></p>
    <p><%= @store.location %></p>
    <p><%= @store.contact_info %></p>
 </div>
<div>
    <%= form_for [@store, @comment] do |c| %>
        <%= c.label :comment %>
        <%= c.text_field :comment, "size"=> 60, "height"=> 30%>
        <%= c.submit %>
    <% end %>
</div>
    
<p> Average rating: <%= average_rating(@store) %>  </p>
<div>
   <%= link_to image_tag("1s.png", {width: 30}), store_ratings_path(@store, rating:1), method: :post %>
   <%= link_to image_tag("2s.png", {width: 30}), store_ratings_path(@store, rating:2), method: :post %>
   <%= link_to image_tag("3s.png", {width: 30}), store_ratings_path(@store, rating:3), method: :post %>
   <%= link_to image_tag("4s.png", {width: 30}), store_ratings_path(@store, rating:4), method: :post %>
   <%= link_to image_tag("5s.png", {width: 30}), store_ratings_path(@store, rating:5), method: :post %>
 
</div>  
<div>
    <% @store.comments.each do |content| %>
        <div class="bckclr2">
        <dd> <%= content.comment %> <dd>
        By: <%= content.user.name %>
        <%= content.created_at.strftime("%b %d %Y") %>
        <%= link_to "Delete", comment_path(content), method: :delete %>
        </div>
    <% end %>
</div>  
<div><%= link_to "Lets take a trip back", stores_path %></div>

<div>
    <%= link_to "Remove Store!", store_path(@store), method: :delete, data: { confirm: "Verify please"} %>&nbsp;&nbsp;&nbsp;
    <%= link_to "Edit Store", edit_store_path %>
</div>

app/views/swirls/index.html.erb
<div class="swirls">
    <h1 id="title-word">Swirls of Joy</h1>
    <h3 class="font2">"My head says go to the gym,<br>MY HEART SAYS eat more ice cream" </h3>
    <%= image_tag "ice_cover.jpg", {width: 500}%> 
    <h3 class="linker">
        <div class="button">
            <%= link_to 'OC/LA LOCATIONS', stores_path %>
            &nbsp;&nbsp;&nbsp;&nbsp     
            <%= link_to 'I am feeling lucky', stores_random_path %>
        </div>
    </h3>
</div>

app/views/users/new.html.erb
<div class="text-center">
<div class="font2"><h1>Sign Up</h1></div>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>&nbsp&nbsp
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>&nbsp&nbsp
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>&nbsp&nbsp&nbsp&nbsp&nbsp
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

<p>Have an account?<%= link_to "Sign in", login_path %></p>

</div>